#!/bin/bash

name=${1%.*}
sk=${1%.*}.sk
tex=${1%.*}.tex
pdf=${1%.*}.pdf
ppm=${1%.*}-1.ppm
png=${1%.*}.png
ps=${1%.*}-pics.ps
dvi=${1%.*}.dvi

../sketch -Te $sk -o $tex
pdflatex -shell-espace --enable-write18 $tex
latex $tex
dvips -o $ps $dvi
ps2pdf $ps
pdflatex -shell-espace --enable-write18 $tex
pdfcrop $pdf $pdf -margins "5 5 5 5"
pdftoppm $pdf $name
convert $ppm $png

echo "Removing temporary files..."
rm -v $ppm
rm -v ${name}.aux
rm -v ${name}.log
rm -v $dvi
rm -v $ps
rm -v $tex
rm -v ${name}-pics.pdf
rm -v $pdf
